### ISSUE TITLE
How to train?

### ISSUE THREAD

**Issue by SnailForce** [jeolpyeoni/StyleCineGAN#2]
Hello, I wanna to know how to train and which dataset used?

**Comment by jeolpyeoni** [comment]
Hello, thank you for showing interest in our work.

The implementation details for training each module are provided in the main paper and supplementary material. You can refer to these documents at the following link: https://jeolpyeoni.github.io/stylecinegan_project/

To answer briefly, we trained StyleGAN2 and feature-style encoder models on LHQ dataset,
and trained pix2pixHD model on both Sky-Timelapse and Eulerian datasets as a motion generator.
For the mask predictor, we trained datasetGAN with a few (in our case, 10) selected samples from LHQ dataset, making pairs with manually annotated masks obtained using Segment Anything.
